### ISSUE TITLE
Create service layer

### ISSUE THREAD

**Issue by dBucik** [LizzardCorp/pb138project#13]
Service layer will prepare data from persistence layer for displaying in UI.

**Comment by dBucik** [comment]
For the Person entity the web layer will need methods capable to perform following operations
* find person by id
* create person entry in DB
* edit person entry read and stored to DB
* delete person entry from DB

**Comment by dBucik** [comment]
For the Invoice entity the web layer will need methods capabe to perform following operations
* getInvoiceById(Long id) - get Invoice entry from DB with specified ID
* getInvoicesInDateInterval(LocalDate oldest, LocalDate newest) - get all Invoices from DB that have date when issued after "oldest" (including) but before "newest" (including)
* getInvoicesByType(LocalDate oldest, LocalDate newest, InvoiceType type) - get all Invoices from DB that have specified type and have date when issued after "oldest" (including) but before "newest" (including)
* getInvoicesByPersonId(LocalDate oldest, LocalDate newest, Long personId) - get all Invoices from DB that have specified id of Person in either "buyer" or "seller" and have date when issued after "oldest" (including) but before "newest" (including)
* getInvoicesByPersonIdAndType(LocalDate oldest, LocalDate newest, Long personId, InvoiceType type) - get all Invoices from DB that have specified type and Person ID in "payer" if type is "EXPENSE"  or in "recipient" if type is "INCOME"
* createInvoice(Invoice invoice) - store Invoice object to the DB
* editInvoice(Invoice invoice) - store edited Invoice object into DB (update old one)
* deleteInvoice(Invoice invoice) - delete Invoice object from DB

**Comment by balcirakpeter** [comment]
Service layer is implemented so I am closing this issue.
